### ISSUE TITLE
Alignments as in the mockup

### ISSUE THREAD

**Issue by bhawesh96** [sidharthramesh/annie#15]
1) Banner text on the right is to be left aligned as in the mock-up
2) Section right above the footer (Make learning inclusive). Even that is to be aligned as in the mock-up.

**Comment by sidharthramesh** [comment]
Alright. Get the alignment requirements for mobile. I'll push these changes soon.

**Comment by sidharthramesh** [comment]
Also, in the mockup, the main annie image had a reflection. We weren't really fond of that so removed it, but if the client wants it just replace 'annie-main.jpg' to 'annie-main_reflection.jpg' and you'll be good to go.

**Comment by sidharthramesh** [comment]
Will reopen the issue if mobile alignments also need change
