### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by bhawesh96** [sidharthramesh/annie#6]
![fontsss](https://user-images.githubusercontent.com/17593065/34717186-2b0b0420-f558-11e7-8cd6-9f29fea4465d.PNG)

Client liked this combination
Heading - "librebaskerville-bold"
Sub Heading - "montserrat-bold"
Other content (<p> etc) - "montserrat-regular"

**Comment by sidharthramesh** [comment]
Please post the fonts on the mockup here
