### ISSUE TITLE
Carousel for 'clients' section

### ISSUE THREAD

**Issue by bhawesh96** [sidharthramesh/annie#8]
![screenshot from 2018-01-09 23-37-53](https://user-images.githubusercontent.com/17593065/34735673-47610b4a-f596-11e7-9846-bdb67d34ee20.png)

A smooth marquee like infinite carousel is needed by the client

**Comment by sidharthramesh** [comment]
Don't they want the carousel?

**Comment by bhawesh96** [comment]
It should slide automatically is what they want
